package com.sample.rules;

import com.sample.GUI;

declare State
    tresc_pytania : String
    opcje_odpowiedzi : String[]
    odpowiedz : String
end

rule "query"
    when
        state : State(opcje_odpowiedzi != null && opcje_odpowiedzi.length > 0)
    then
        GUI gui = new GUI(state.getTresc_pytania(), state.getOpcje_odpowiedzi());
        gui.waitForAnswer();
        state.setOdpowiedz(gui.getAnswer());
        update(state);
end

rule "endstate"
    when
        state : State(opcje_odpowiedzi.length == 0)
    then
        GUI gui = new GUI(state.getTresc_pytania(), 0);
end

rule "start"
    when
    then
        State decision = new State();
        decision.setTresc_pytania("What kind of preexisting relation do you have with this person?");
        decision.setOpcje_odpowiedzi(new String[] {"PROFESIONAL", "PERSONAL", "OTHER"});
        insert(decision);
end

rule "What kind of preexisting relation do you have with this person? - PROFESIONAL"
    when
        decision : State(odpowiedz == "PROFESIONAL",
                         tresc_pytania == "What kind of preexisting relation do you have with this person?")
    then
        decision.setTresc_pytania("What kind of professional relation do you have?");
        decision.setOpcje_odpowiedzi(new String[] {"PROFESSOR.png", "STUDENT.png", "TEACHER.png", "BOSS.png", "PHYSICIAN.png",
                                                "LANDLORD.png", "SOCIAL_WORKER.png", "THERAPIST.png", "STALKER.png", "COSTAR.png"});
        update(decision);
end

rule "What kind of preexisting relation do you have with this person? - PERSONAL"
    when
        decision : State(odpowiedz == "PERSONAL",
                         tresc_pytania == "What kind of preexisting relation do you have with this person?")
    then
        decision.setTresc_pytania("Are you related?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes", "No"});
        update(decision);
end

rule "What kind of preexisting relation do you have with this person? - OTHER"
    when
        decision : State(odpowiedz == "OTHER",
                         tresc_pytania == "What kind of preexisting relation do you have with this person?")
    then
        decision.setTresc_pytania("Then what is it?");
        decision.setOpcje_odpowiedzi(new String[] {"GHOST", "BEST_FRIENDS_EX", "CONSOLE", "PET", "LOVEBOT"});
        update(decision);
end

rule "Are you related? - NO"
    when
        decision : State(odpowiedz == "No",
                         tresc_pytania == "Are you related?")
    then
        decision.setTresc_pytania("So What kind of personal relation do you have with this person?");
        decision.setOpcje_odpowiedzi(new String[] {"MISSED_CONNECTION", "BEST_FRIENDS_SIBLING", "DEALER", "ROOMMATE", 
                                                "SOULMATE", "CELLMATE", "DUNGEON_MASTER", "CRUSH"});
        update(decision);
end

rule "landlord"
    when 
        decision : State(odpowiedz == "LANDLORD.png",
                         tresc_pytania == "What kind of professional relation do you have?")
    then
        decision.setTresc_pytania("Do you live either in San Francisco or New York?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes", "No"});
        update(decision);
end

rule "SF or NY-yes"
    when 
        decision : State(odpowiedz == "Yes",
                         tresc_pytania == "Do you live either in San Francisco or New York?")
    then
        decision.setTresc_pytania("WHATEVER_IT_TAKES.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "SF or NY-no"
	when 
		decision : State(odpowiedz == "No",
                         tresc_pytania == "Do you live either in San Francisco or New York?")
    then
        decision.setTresc_pytania("PROBABLY_BETTER_NOT.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "social worker"
    when 
        decision : State(odpowiedz == "SOCIAL_WORKER.png",
                         tresc_pytania == "What kind of professional relation do you have?")
    then
        decision.setTresc_pytania("Is this attempt to get your kids back?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes", "No"});
        update(decision);
end

rule "getting kids back - yes"
    when 
        decision : State(odpowiedz == "Yes",
                         tresc_pytania == "Is this attempt to get your kids back?")
    then
        decision.setTresc_pytania("WHATEVER_IT_TAKES.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "getting kids back - no"
	when 
		decision : State(odpowiedz == "No",
                         tresc_pytania == "Is this attempt to get your kids back?")
    then
        decision.setTresc_pytania("PROBABLY_BETTER_NOT.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "therapist"
    when 
        decision : State(odpowiedz == "THERAPIST.png",
                         tresc_pytania == "What kind of professional relation do you have?")
    then
        decision.setTresc_pytania("ARE YOU CRAZY?");
        decision.setOpcje_odpowiedzi(new String[] {"Maybe a little", "I don't think so"});
        update(decision);
end

rule "ARE YOU CRAZY - yes"
    when 
        decision : State(odpowiedz == "Maybe a little",
                         tresc_pytania == "ARE YOU CRAZY?")
    then
        decision.setTresc_pytania("PROBABLY_BETTER_NOT.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "ARE YOU CRAZY - no"
	when 
		decision : State(odpowiedz == "I don't think so",
                         tresc_pytania == "ARE YOU CRAZY?")
    then
        decision.setTresc_pytania("");
        decision.setOpcje_odpowiedzi(new String[] {"HANDSHAKE.png"});
        update(decision);
end

rule "HANDSHAKE"
	when 
		decision : State(odpowiedz == "HANDSHAKE.png")
    then
        decision.setTresc_pytania("");
        decision.setOpcje_odpowiedzi(new String[] {"SRUBA.png","KOSC.png"});
        update(decision);
end

rule "KOSC"
	when 
		decision : State(odpowiedz == "KOSC.png")
    then
        decision.setTresc_pytania("");
        decision.setOpcje_odpowiedzi(new String[] {"SRUBA.png","HANDSHAKE.png"});
        update(decision);
end

rule "SRUBA"
	when 
		decision : State(odpowiedz == "SRUBA.png")
    then
        decision.setTresc_pytania("");
        decision.setOpcje_odpowiedzi(new String[] {"KOSC.png","HANDSHAKE.png"});
        update(decision);
end

rule "stalker"
    when 
        decision : State(odpowiedz == "STALKER.png",
                         tresc_pytania == "What kind of professional relation do you have?")
    then
        decision.setTresc_pytania("Is there restraining order involved?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes", "No"});
        update(decision);
end

rule "Restraining order - no"
    when 
        decision : State(odpowiedz == "No",
                         tresc_pytania == "Is there restraining order involved?")
    then
        decision.setTresc_pytania("PROBABLY_BETTER_NOT.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Restraining order - yes"
	when 
		decision : State(odpowiedz == "Yes",
                         tresc_pytania == "Is there restraining order involved?")
    then
        decision.setTresc_pytania("When are you gonna realise I'm the only one who's gonna loves you?");
        decision.setOpcje_odpowiedzi(new String[] {"Never","Today"});
        update(decision);
end

rule "only one - today"
    when 
        decision : State(odpowiedz == "Today",
                         tresc_pytania == "When are you gonna realise I'm the only one who's gonna loves you?")
    then
        decision.setTresc_pytania("");
        decision.setOpcje_odpowiedzi(new String[] {"HANDSHAKE.png"});
        update(decision);
end

rule "only one - never"
    when 
        decision : State(odpowiedz == "Never",
                         tresc_pytania == "When are you gonna realise I'm the only one who's gonna loves you?")
    then
        decision.setTresc_pytania("PROBABLY_BETTER_NOT.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end



