package com.sample.rules;

import com.sample.GUI;

declare State
    tresc_pytania : String
    opcje_odpowiedzi : String[]
    odpowiedz : String
end

rule "query"
    when
        state : State(opcje_odpowiedzi != null && opcje_odpowiedzi.length > 0)
    then
        GUI gui = new GUI(state.getTresc_pytania(), state.getOpcje_odpowiedzi());
        gui.waitForAnswer();
        state.setOdpowiedz(gui.getAnswer());
        update(state);
end

rule "endstate"
    when
        state : State(opcje_odpowiedzi.length == 0)
    then
        GUI gui = new GUI(state.getTresc_pytania(), 0);
end

rule "start"
    when
    then
        State decision = new State();
        decision.setTresc_pytania("What kind of preexisting relation do you have with this person?");
        decision.setOpcje_odpowiedzi(new String[] {"PROFESIONAL", "PERSONAL", "OTHER"});
        insert(decision);
end

rule "What kind of preexisting relation do you have with this person? - PROFESIONAL"
    when
        decision : State(odpowiedz == "PROFESIONAL",
                         tresc_pytania == "What kind of preexisting relation do you have with this person?")
    then
        decision.setTresc_pytania("What kind of professional relation do you have?");
        decision.setOpcje_odpowiedzi(new String[] {"PROFESSOR.png", "STUDENT.png", "TEACHER.png", "BOSS.png", "PHYSICIAN.png",
                                                "LANDLORD.png", "SOCIAL_WORKER.png", "THERAPIST.png", "STALKER.png", "COSTAR.png"});
        update(decision);
end

rule "What kind of preexisting relation do you have with this person? - PERSONAL"
    when
        decision : State(odpowiedz == "PERSONAL",
                         tresc_pytania == "What kind of preexisting relation do you have with this person?")
    then
        decision.setTresc_pytania("Are you related?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes", "No"});
        update(decision);
end

rule "What kind of preexisting relation do you have with this person? - OTHER"
    when
        decision : State(odpowiedz == "OTHER",
                         tresc_pytania == "What kind of preexisting relation do you have with this person?")
    then
        decision.setTresc_pytania("Then what is it?");
        decision.setOpcje_odpowiedzi(new String[] {"GHOST.png", "BEST_FRIENDS_EX.png", "CONSOLE.png", "PET.png", "LOVEBOT.png"});
        update(decision);
end

rule "Are you related? - NO"
    when
        decision : State(odpowiedz == "No",
                         tresc_pytania == "Are you related?")
    then
        decision.setTresc_pytania("So What kind of personal relation do you have with this person?");
        decision.setOpcje_odpowiedzi(new String[] {"MISSED_CONNECTION.png", "BEST_FRIENDS_SIBLING.png", "DEALER.png", "ROOMMATE.png", 
                                                "SOULMATE.png", "CELLMATE.png", "DUNGEON_MASTER.png", "CRUSH.png"});
        update(decision);
end

rule "Are you related? - YES"
    when
        decision : State(odpowiedz == "Yes",
                         tresc_pytania == "Are you related?")
    then
        decision.setTresc_pytania("By blood?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes", "No"});
        update(decision);
end

rule "By blood? - YES"
    when
        decision : State(odpowiedz == "Yes",
                         tresc_pytania == "By blood?")
    then
        decision.setTresc_pytania("Close or far?");
        decision.setOpcje_odpowiedzi(new String[] {"It's my brother/sister", "It's my second cousin"});
        update(decision);
end

rule "Close or far? - brother/siste"
    when
        decision : State(odpowiedz == "It's my brother/sister",
                         tresc_pytania == "Close or far?")
    then
        decision.setTresc_pytania("ABSOLUTELY_NO.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Close or far? - second cousin"
    when
        decision : State(odpowiedz == "It's my second cousin",
                         tresc_pytania == "Close or far?")
    then
        decision.setTresc_pytania("Are you really in love or just desperate?");
        decision.setOpcje_odpowiedzi("God, I am so desperate", "No, It's really love I'm sure");
        update(decision);
end

rule "Are you really in love or just desperate? - God, I am so desperate"
    when
        decision : State(odpowiedz == "God, I am so desperate",
                         tresc_pytania == "Are you really in love or just desperate?")
    then
        decision.setTresc_pytania("Hang_in_there.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Are you really in love or just desperate? - No, It's really love I'm sure"
    when
        decision : State(odpowiedz == "No, It's really love I'm sure",
                         tresc_pytania == "Are you really in love or just desperate?")
    then
        decision.setTresc_pytania("Do you live in a sparsely populated area? Or the South?");
        decision.setOpcje_odpowiedzi("Yes", "No");
        update(decision);
end

rule "Do you live in a sparsely populated area? Or the South? - No"
    when
        decision : State(odpowiedz == "No",
                         tresc_pytania == "Do you live in a sparsely populated area? Or the South?")
    then
        decision.setTresc_pytania("Hang_in_there.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Do you live in a sparsely populated area? Or the South? - No"
    when
        decision : State(odpowiedz == "No",
                         tresc_pytania == "Do you live in a sparsely populated area? Or the South?")
    then
        decision.setTresc_pytania("DOWNLOW.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "By blood? - NO"
    when
        decision : State(odpowiedz == "No",
                         tresc_pytania == "By blood?")
    then
        decision.setTresc_pytania("Close or far?");
        decision.setOpcje_odpowiedzi(new String[] {"Brothers_wifes_cousin.png", "Step.png"});
        update(decision);
end

rule "Close or far? - Brothers_wifes_cousin"
    when
        decision : State(odpowiedz == "Brothers_wifes_cousin.png",
                         tresc_pytania == "Close or far?")
    then
        decision.setTresc_pytania("Make_it.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Close or far? - Step.png"
    when
        decision : State(odpowiedz == "Step.png",
                         tresc_pytania == "Close or far?")
    then
        decision.setTresc_pytania("Are the parents still maried?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes","No"});
        update(decision);
end

rule "Are the parents still maried? - no"
    when
        decision : State(odpowiedz == "No",
                         tresc_pytania == "Are the parents still maried?")
    then
        decision.setTresc_pytania("Did you grow up together, like from childhood?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes","No"});
        update(decision);
end

rule "Did you grow up together, like from childhood? - no"
    when
        decision : State(odpowiedz == "No",
                         tresc_pytania == "Did you grow up together, like from childhood?")
    then
        decision.setTresc_pytania("DOWNLOW.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Did you grow up together, like from childhood? - yes"
    when
        decision : State(odpowiedz == "Yes",
                         tresc_pytania == "Did you grow up together, like from childhood?")
    then
        decision.setTresc_pytania("ABSOLUTELY_NO.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Are the parents still maried? - Yes"
    when
        decision : State(odpowiedz == "Yes",
                         tresc_pytania == "Are the parents still maried?")
    then
        decision.setTresc_pytania("Are you Woody Allen?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes","No"});
        update(decision);
end

rule "Are you Woody Allen? - Yes"
    when
        decision : State(odpowiedz == "Yes",
                         tresc_pytania == "Are you Woody Allen?")
    then
        decision.setTresc_pytania("Make_it.png");
        decision.setOpcje_odpowiedzi(new String[] {"Yes","No"});
        update(decision);
end

rule "Are you Woody Allen? - No"
    when
        decision : State(odpowiedz == "No",
                         tresc_pytania == "Are you Woody Allen?")
    then
        decision.setTresc_pytania("ABSOLUTELY_NO.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Highshool crush"
    when 
        decision : State(odpowiedz == "CRUSH.png",
                         tresc_pytania == "So What kind of personal relation do you have with this person?")
    then
        decision.setTresc_pytania("Disgust.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "DUNGEON_MASTER"
    when 
        decision : State(odpowiedz == "DUNGEON_MASTER.png",
                         tresc_pytania == "So What kind of personal relation do you have with this person?")
    then
        decision.setTresc_pytania("sex_with_dm.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "CELLMATE"
    when 
        decision : State(odpowiedz == "CELLMATE.png",
                         tresc_pytania == "So What kind of personal relation do you have with this person?")
    then
        decision.setTresc_pytania("Do you really have a choise in a matter?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes", "No"});
        update(decision);
end

rule "Do you really have a choise in a matter? - No"
    when 
        decision : State(odpowiedz == "No",
                         tresc_pytania == "Do you really have a choise in a matter?")
    then
        decision.setTresc_pytania("Obvious.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Do you really have a choise in a matter? - Yes"
    when 
        decision : State(odpowiedz == "Yes",
                         tresc_pytania == "Do you really have a choise in a matter?")
    then
        decision.setTresc_pytania("PROBABLY_BETTER_NOT.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "SOULMATE"
    when 
        decision : State(odpowiedz == "SOULMATE.png",
                         tresc_pytania == "So What kind of personal relation do you have with this person?")
    then
        decision.setTresc_pytania("Are you done having sex with other people?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes", "No"});
        update(decision);
end

rule "Are you done having sex with other people? - Yes"
    when 
        decision : State(odpowiedz == "Yes",
                         tresc_pytania == "Are you done having sex with other people?")
    then
        decision.setTresc_pytania("Obvious.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Are you done having sex with other people? - No"
    when 
        decision : State(odpowiedz == "No",
                         tresc_pytania == "Are you done having sex with other people?")
    then
        decision.setTresc_pytania("PROBABLY_BETTER_NOT.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "ROOMMATE"
    when 
        decision : State(odpowiedz == "ROOMMATE.png",
                         tresc_pytania == "So What kind of personal relation do you have with this person?")
    then
        decision.setTresc_pytania("Do you like drama?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes", "No"});
        update(decision);
end

rule "Do you like drama? - No"
    when 
        decision : State(odpowiedz == "No",
                         tresc_pytania == "Do you like drama?")
    then
        decision.setTresc_pytania("PROBABLY_BETTER_NOT.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Do you like drama? - Yes"
    when 
        decision : State(odpowiedz == "Yes",
                         tresc_pytania == "Do you like drama?")
    then
        decision.setTresc_pytania("Awesome.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "DEALER"
    when 
        decision : State(odpowiedz == "DEALER.png",
                         tresc_pytania == "So What kind of personal relation do you have with this person?")
    then
        decision.setTresc_pytania("Do you wanna get high?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes", "No"});
        update(decision);
end

rule "Do you wanna get high? - No"
    when 
        decision : State(odpowiedz == "No",
                         tresc_pytania == "Do you wanna get high?")
    then
        decision.setTresc_pytania("PROBABLY_BETTER_NOT.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Do you wanna get high? - Yes"
    when 
        decision : State(odpowiedz == "Yes",
                         tresc_pytania == "Do you wanna get high?")
    then
        decision.setTresc_pytania("HAPPY-END.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "BEST_FRIENDS_SIBLING"
    when 
        decision : State(odpowiedz == "BEST_FRIENDS_SIBLING.png",
                         tresc_pytania == "So What kind of personal relation do you have with this person?")
    then
        decision.setTresc_pytania("Are you crazy?");
        decision.setOpcje_odpowiedzi(new String[] {"I don't think so", "A little"});
        update(decision);
end

rule "Are you crazy? - I don't think so"
    when 
        decision : State(odpowiedz == "I don't think so",
                         tresc_pytania == "Are you crazy?")
    then
        decision.setTresc_pytania("BAD_LIAR.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Are you crazy? - A little"
    when 
        decision : State(odpowiedz == "A little",
                         tresc_pytania == "Are you crazy?")
    then
        decision.setTresc_pytania("HAPPY-END.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "MISSED_CONNECTION"
    when 
        decision : State(odpowiedz == "MISSED_CONNECTION.png",
                         tresc_pytania == "So What kind of personal relation do you have with this person?")
    then
        decision.setTresc_pytania("How lonley are you?");
        decision.setOpcje_odpowiedzi(new String[] {"Not at all", "A little"});
        update(decision);
end

rule "Are you crazy? - Not at all"
    when 
        decision : State(odpowiedz == "Not at all",
                         tresc_pytania == "Are you crazy?")
    then
        decision.setTresc_pytania("BAD_LIAR.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Are you crazy? - A little"
    when 
        decision : State(odpowiedz == "A little",
                         tresc_pytania == "Are you crazy?")
    then
        decision.setTresc_pytania("HAPPY-END.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "landlord"
    when 
        decision : State(odpowiedz == "LANDLORD.png",
                         tresc_pytania == "What kind of professional relation do you have?")
    then
        decision.setTresc_pytania("Do you live either in San Francisco or New York?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes", "No"});
        update(decision);
end

rule "SF or NY-yes"
    when 
        decision : State(odpowiedz == "Yes",
                         tresc_pytania == "Do you live either in San Francisco or New York?")
    then
        decision.setTresc_pytania("WHATEVER_IT_TAKES.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "SF or NY-no"
	when 
		decision : State(odpowiedz == "No",
                         tresc_pytania == "Do you live either in San Francisco or New York?")
    then
        decision.setTresc_pytania("PROBABLY_BETTER_NOT.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "social worker"
    when 
        decision : State(odpowiedz == "SOCIAL_WORKER.png",
                         tresc_pytania == "What kind of professional relation do you have?")
    then
        decision.setTresc_pytania("Is this attempt to get your kids back?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes", "No"});
        update(decision);
end

rule "getting kids back - yes"
    when 
        decision : State(odpowiedz == "Yes",
                         tresc_pytania == "Is this attempt to get your kids back?")
    then
        decision.setTresc_pytania("WHATEVER_IT_TAKES.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "getting kids back - no"
	when 
		decision : State(odpowiedz == "No",
                         tresc_pytania == "Is this attempt to get your kids back?")
    then
        decision.setTresc_pytania("PROBABLY_BETTER_NOT.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "therapist"
    when 
        decision : State(odpowiedz == "THERAPIST.png",
                         tresc_pytania == "What kind of professional relation do you have?")
    then
        decision.setTresc_pytania("ARE YOU CRAZY?");
        decision.setOpcje_odpowiedzi(new String[] {"Maybe a little", "I don't think so"});
        update(decision);
end

rule "ARE YOU CRAZY - yes"
    when 
        decision : State(odpowiedz == "Maybe a little",
                         tresc_pytania == "ARE YOU CRAZY?")
    then
        decision.setTresc_pytania("PROBABLY_BETTER_NOT.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "ARE YOU CRAZY - no"
	when 
		decision : State(odpowiedz == "I don't think so",
                         tresc_pytania == "ARE YOU CRAZY?")
    then
        decision.setTresc_pytania("");
        decision.setOpcje_odpowiedzi(new String[] {"HANDSHAKE.png"});
        update(decision);
end

rule "HANDSHAKE"
	when 
		decision : State(odpowiedz == "HANDSHAKE.png")
    then
        decision.setTresc_pytania("");
        decision.setOpcje_odpowiedzi(new String[] {"SRUBA.png","KOSC.png"});
        update(decision);
end

rule "KOSC"
	when 
		decision : State(odpowiedz == "KOSC.png")
    then
        decision.setTresc_pytania("");
        decision.setOpcje_odpowiedzi(new String[] {"SRUBA.png","HANDSHAKE.png"});
        update(decision);
end

rule "SRUBA"
	when 
		decision : State(odpowiedz == "SRUBA.png")
    then
        decision.setTresc_pytania("");
        decision.setOpcje_odpowiedzi(new String[] {"KOSC.png","HANDSHAKE.png"});
        update(decision);
end

rule "stalker"
    when 
        decision : State(odpowiedz == "STALKER.png",
                         tresc_pytania == "What kind of professional relation do you have?")
    then
        decision.setTresc_pytania("Is there restraining order involved?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes", "No"});
        update(decision);
end

rule "Restraining order - no"
    when 
        decision : State(odpowiedz == "No",
                         tresc_pytania == "Is there restraining order involved?")
    then
        decision.setTresc_pytania("PROBABLY_BETTER_NOT.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Restraining order - yes"
	when 
		decision : State(odpowiedz == "Yes",
                         tresc_pytania == "Is there restraining order involved?")
    then
        decision.setTresc_pytania("When are you gonna realise I'm the only one who's gonna loves you?");
        decision.setOpcje_odpowiedzi(new String[] {"Never","Today"});
        update(decision);
end

rule "only one - today"
    when 
        decision : State(odpowiedz == "Today",
                         tresc_pytania == "When are you gonna realise I'm the only one who's gonna loves you?")
    then
        decision.setTresc_pytania("");
        decision.setOpcje_odpowiedzi(new String[] {"HANDSHAKE.png"});
        update(decision);
end

rule "only one - never"
    when 
        decision : State(odpowiedz == "Never",
                         tresc_pytania == "When are you gonna realise I'm the only one who's gonna loves you?")
    then
        decision.setTresc_pytania("PROBABLY_BETTER_NOT.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Costar"
    when 
        decision : State(odpowiedz == "COSTAR.png",
                         tresc_pytania == "What kind of professional relation do you have?")
    then
        decision.setTresc_pytania("Are you trying to generate publicity and dispel certain rumors?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes", "No"});
        update(decision);
end

rule "Publicity-yes"
    when 
        decision : State(odpowiedz == "Yes",
                         tresc_pytania == "Are you trying to generate publicity and dispel certain rumors?")
    then
        decision.setTresc_pytania("PATISON.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Publicity-no"
	when 
		decision : State(odpowiedz == "No",
                         tresc_pytania == "Are you trying to generate publicity and dispel certain rumors?")
    then
        decision.setTresc_pytania("SEX_TAPE.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "PHYSICIAN"
    when 
        decision : State(odpowiedz == "PHYSICIAN.png",
                         tresc_pytania == "What kind of professional relation do you have?")
    then
        decision.setTresc_pytania("Is your health at any serious risk?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes", "No"});
        update(decision);
end

rule "Health risk - yes"
    when 
        decision : State(odpowiedz == "Yes",
                         tresc_pytania == "Is your health at any serious risk?")
    then
        decision.setTresc_pytania("PROBABLY_BETTER_NOT.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Health risk - no"
	when 
		decision : State(odpowiedz == "No",
                         tresc_pytania == "Is your health at any serious risk?")
    then
        decision.setTresc_pytania("HANDSHAKE.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "BOSS"
    when 
        decision : State(odpowiedz == "BOSS.png",
                         tresc_pytania == "What kind of professional relation do you have?")
    then
        decision.setTresc_pytania("Does your job suck?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes", "No"});
        update(decision);
end

rule "Sucking job - yes"
    when 
        decision : State(odpowiedz == "Yes",
                         tresc_pytania == "Does your job suck?")
    then
        decision.setTresc_pytania("KOSC.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Sucking job - no"
	when 
		decision : State(odpowiedz == "No",
                         tresc_pytania == "Does your job suck?")
    then
        decision.setTresc_pytania("PROBABLY_BETTER_NOT.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Professor"
	when
		decision : State(odpowiedz == "Professor.png",
                         tresc_pytania == "What kind of professional relation do you have?")

    then
        decision.setTresc_pytania("KOSC.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Teacher"
	when
		decision : State(odpowiedz == "TEACHER.png",
                         tresc_pytania == "What kind of professional relation do you have?")
	  then
        decision.setTresc_pytania("ABSOLUTELY_NO.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Student"
	when
		decision : State(odpowiedz == "STUDENT.png",
                         tresc_pytania == "What kind of professional relation do you have?")
	  then
        decision.setTresc_pytania("Where do you teach?");
        decision.setOpcje_odpowiedzi(new String[] {"College", "Anything below college"});
        update(decision);
end

rule "College"
    when 
        decision : State(odpowiedz == "College",
                         tresc_pytania == "Where do you teach?")
    then
        decision.setTresc_pytania("Does your job suck?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes", "No"});
        update(decision);
end

rule "Below college"
	when 
		decision : State(odpowiedz == "Anything below college",
                         tresc_pytania == "Where do you teach?")
    then
        decision.setTresc_pytania("WHOA. You're talking about having sex with a minor, right?");
        decision.setOpcje_odpowiedzi(new String[] {"YEAH", "NO, of course not"});
        update(decision);
end

rule "Thought crime"
	when 
		decision : State(//odpowiedz == "YEAH" ,
		 tresc_pytania== "WHOA. You're talking about having sex with a minor, right?")
    then
        decision.setTresc_pytania("THOUGHT_CRIME.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "GHOST"
	when
		decision : State(odpowiedz == "GHOST.png",
                         tresc_pytania == "Then what is it?")
	  then
        decision.setTresc_pytania("Like Demi Moore/Patrick Swayze movie?");
        decision.setOpcje_odpowiedzi(new String[] {"Yeah, exactly like that!", "No, it's really nothing like that!"});
        update(decision);
end

rule "Patrick swayze movie - yes"
	when
		decision : State(odpowiedz == "Yeah, exactly like that!",
                         tresc_pytania == "Like Demi Moore/Patrick Swayze movie?")
	  then
        decision.setTresc_pytania("GHOST_HUGGING.png");
        decision.setOpcje_odpowiedzi(new String[] {""});
        update(decision);
end

rule "Patrick swayze movie - no"
	when
		decision : State(odpowiedz == "No, it's really nothing like that!",
                         tresc_pytania == "Like Demi Moore/Patrick Swayze movie?")
	  then
        decision.setTresc_pytania("Would you have dated this person when among living?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes", "No"});
        update(decision);
end

rule "Dating alive - no"
	when
		decision : State(odpowiedz == "No",
                         tresc_pytania == "Would you have dated this person when among living?")
	  then
        decision.setTresc_pytania("PROBABLY_BETTER_NOT.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Dating alive - yes"
	when
		decision : State(odpowiedz == "Yes",
                         tresc_pytania == "Would you have dated this person when among living?")
	  then
        decision.setTresc_pytania("GHOST_HUGGING.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end
	

rule "Best Friends Ex"
	when
		decision : State(odpowiedz == "BEST_FRIENDS_EX.png",
                         tresc_pytania == "Then what is it?")
	  then
        decision.setTresc_pytania("How long since they stopped dating?");
        decision.setOpcje_odpowiedzi(new String[] {"Well, technically they haven't, really...", "Oh, it's been a while"});
        update(decision);
end

rule "are they together - yes"
	when
		decision : State(odpowiedz == "Well, technically they haven't, really...",
                         tresc_pytania == "How long since they stopped dating?")
	  then
        decision.setTresc_pytania("ABSOLUTELY_NO.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "are they together - no"
	when
		decision : State(odpowiedz == "Oh, it's been a while",
                         tresc_pytania == "How long since they stopped dating?")
	 then
        decision.setTresc_pytania("Are they still friends? Or enemies?");
        decision.setOpcje_odpowiedzi(new String[] {"They have sworn to kill each other on sight", "They're friendly enough"});
        update(decision);
end

rule "Still friends"
	when
		decision : State(odpowiedz == "They're friendly enough",
                         tresc_pytania == "Are they still friends? Or enemies?")
	 then
        decision.setTresc_pytania("BROS_BEFORE_HOS.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "ENEMIES"
	when
		decision : State(odpowiedz == "They have sworn to kill each other on sight",
                         tresc_pytania == "Are they still friends? Or enemies?")
	  then
        decision.setTresc_pytania("ABSOLUTELY_NO.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Console"
	when
		decision : State(odpowiedz == "CONSOLE.png",
                         tresc_pytania == "Then what is it?")
	  then
        decision.setTresc_pytania("How old are you again?");
        decision.setOpcje_odpowiedzi(new String[] {"I'm over 18", "I'm under 18"});
        update(decision);
end

rule "Adult"
	when
		decision : State(odpowiedz == "I'm over 18",
                         tresc_pytania == "How old are you again?")
	  then
        decision.setTresc_pytania("Do you want to be allone for ther rest of your life?");
        decision.setOpcje_odpowiedzi(new String[] {"Yes", "No"});
        update(decision);
end

rule "Forever alone"
	when
		decision : State(odpowiedz == "Yes",
                         tresc_pytania == "Do you want to be allone for ther rest of your life?")
	  then
        decision.setTresc_pytania("GAME_ON.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "Not Forever alone "
	when
		decision : State(odpowiedz == "No",
                         tresc_pytania == "Do you want to be allone for ther rest of your life?")
	  then
        decision.setTresc_pytania("TAKE_A_SHOWER.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "kid"
	when
		decision : State(odpowiedz == "I'm under 18",
                         tresc_pytania == "How old are you again?")
	   then
        decision.setTresc_pytania("GAME_ON.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "She's more like a pet to me"
	when
		decision : State(odpowiedz == "PET.png",
                         tresc_pytania == "Then what is it?")
	  then
        decision.setTresc_pytania("Seriously? You want to date an animal");
        decision.setOpcje_odpowiedzi(new String[] {"NO", "YES"});
        update(decision);
end

rule "She's more like a pet to me - no"
	when
		decision : State(odpowiedz == "NO",
                         tresc_pytania == "Seriously? You want to date an animal")
	  then
        decision.setTresc_pytania("Ok, well, not \"date\" per se");
        decision.setOpcje_odpowiedzi(new String[] {""});
        update(decision);
end

rule "Not a date per se"
	when
		decision : State(odpowiedz == "",
                         tresc_pytania == "Ok, well, not \"date\" per se")
	  then
        decision.setTresc_pytania("ABSOLUTELY_NO.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "She's more like a pet to me - yes"
	when
		decision : State(odpowiedz == "YES",
                         tresc_pytania == "Seriously? You want to date an animal")
	  then
        decision.setTresc_pytania("Are you a farmer?");
        decision.setOpcje_odpowiedzi(new String[] {"NO", "YES"});
        update(decision);
end


rule "Farmer"
	when
		decision : State(odpowiedz == "YES",
                         tresc_pytania == "Are you a farmer?")
	  then
        decision.setTresc_pytania("DOWNLOW.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end


rule "Not a Farmer"
	when
		decision : State(odpowiedz == "NO",
                         tresc_pytania == "Are you a farmer?")
	  then
        decision.setTresc_pytania("ABSOLUTELY_NO.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end

rule "LOVEBOT"
	when
		decision : State(odpowiedz == "LOVEBOT.png",
                         tresc_pytania == "Then what is it?")
	  then
        decision.setTresc_pytania("Do you live in Japan?");
        decision.setOpcje_odpowiedzi(new String[] {"NO", "YES"});
        update(decision);
end


rule "Japanese"
	when
		decision : State(odpowiedz == "YES",
                         tresc_pytania == "Do you live in Japan?")
	  then
        decision.setTresc_pytania("DOWNLOW.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end


rule "Not a Japanese"
	when
		decision : State(odpowiedz == "NO",
                         tresc_pytania == "Do you live in Japan?")
	  then
        decision.setTresc_pytania("Will you please move there to make the rest of us feel better?");
        decision.setOpcje_odpowiedzi(new String[] {"NO", "YES"});
        update(decision);
end

rule "Future Japanese"
	when
		decision : State(odpowiedz == "YES",
                         tresc_pytania == "Will you please move there to make the rest of us feel better?")
	  then
        decision.setTresc_pytania("DOWNLOW.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end


rule "Not Future Japanese"
	when
		decision : State(odpowiedz == "NO",
                         tresc_pytania == "Will you please move there to make the rest of us feel better?")
	  then
        decision.setTresc_pytania("ABSOLUTELY_NO.png");
        decision.setOpcje_odpowiedzi(new String[] {});
        update(decision);
end
